using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using Nom.Common;

namespace Nom.Web.Controls
{
	public partial class Head : System.Web.UI.UserControl
	{
		protected override void OnLoad(EventArgs e)
		{
		 	base.OnLoad(e);

			BuildJavaScript();
		}

		private void BuildJavaScript()
		{
			List<string> jsList = new List<string>();
			jsList.Add(string.Format("http://maps.google.com/maps?file=api&v=2&key={0}", Constants.APIKeys.Google.Maps));
			jsList.Add(string.Format("http://www.google.com/uds/api?file=uds.js&v=1.0&key={0}", Constants.APIKeys.Google.Search));

			foreach (string jsItem in jsList)
			{
				HtmlGenericControl script = new HtmlGenericControl("script");
				script.Attributes.Add("type", "text/javascript");
				script.Attributes.Add("src", jsItem);
				
				phAutogeneratedScripts.Controls.Add(script);
			}
		}
	}
}