<%@ Control Language="C#" AutoEventWireup="true" CodeBehind="Head.ascx.cs" Inherits="Nom.Web.Controls.Head" %>
	<script type="text/javascript" src="/Resources/JS/jquery-1.2.6.min.js"></script>
	<script type="text/javascript" src="/Resources/JS/Nom.js"></script>
	<asp:PlaceHolder ID="phAutogeneratedScripts" runat="server" />